# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.4
language: swift
# xcode_workspace: Demirciy.xcworkspace
# xcode_scheme: Demirciy
# xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 11
podfile: Podfile
# cache: cocoapods

notifications:
  slack: demirciy:pzu0mBJfP9CAy16arOxASvjF
  email:
    recipients:
      - demirciy94@gmail.com
    on_success: never
    on_failure: always

before_install:
- brew update
- gem install cocoapods
- pod install

script:
# - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Demirciy.xcworkspace -scheme Demirciy -sdk iphonesimulator13.0 ONLY_ACTIVE_ARCH=NO | xcpretty
# - xcodebuild clean build
- xcodebuild clean build -workspace Demirciy.xcworkspace -scheme Demirciy -sdk iphonesimulator13.0
# - pod lib lint
 
# after_success:
# - fastlane test

branches:
  only:
    - development

    # - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Demirciy.xcworkspace -scheme Demirciy -sdk iphonesimulator13.0 ONLY_ACTIVE_ARCH=NO | xcpretty
