
osx_image: xcode11.4
language: swift
xcode_workspace: Demirciy.xcworkspace
xcode_destination: platform=iOS Simulator,name=iPhone 11
podfile: Podfile

before_install:
- brew update
- pod install

jobs:
  include:
    - name: 'Build & Test Example'
      xcode_scheme: Demirciy
    - name: 'Pod library lint'
      script: 
      - pod lib lint Demirciy.podspec

notifications:
  slack: demirciy:pzu0mBJfP9CAy16arOxASvjF
  email:
    recipients:
      - demirciy94@gmail.com
    on_success: never
    on_failure: always

branches:
  only:
    - development
