
update_fastlane

default_platform(:ios)

platform :ios do
  desc 'Run test'
  lane :test do
    run_tests(workspace: 'Demirciy.xcworkspace',
      scheme: 'DemirciyTest',
      slack_url: 'https://hooks.slack.com/services/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',
      slack_channel: '#fastlane')
  end
end
